name: Build & run E2E tests

on:
  # make the workflow reusable
  workflow_call:
permissions:
  id-token: write
  contents: read
jobs:
  run-e2e-tests:
    strategy:
      matrix:
        browser: ["chromium", "firefox", "chrome", "msedge"]
    runs-on: ubuntu-latest
    steps:
      - name: Clone E2E tests repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          repository: USSF-ORBIT/ussf-portal
          path: ./e2e-tests
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later
          ref: main # checkout main by default

      - name: Checkout E2E ${{github.head_ref}} or main
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        working-directory: ./e2e-tests
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Checkout E2E ${{github.event.merge_group.head_ref}} or main
        if: ${{ github.event_name == 'merge_group' }}
        working-directory: ./e2e-tests
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.event.merge_group.head_ref}} origin/${{github.event.merge_group.head_ref}} || echo "staying on main"

      - name: Clone portal client
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          repository: USSF-ORBIT/ussf-portal-client
          path: ./ussf-portal-client
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later
          ref: main # checkout main by default

      - name: Checkout portal client ${{github.head_ref}} or main
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        working-directory: ./ussf-portal-client
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Checkout portal client ${{github.event.merge_group.head_ref}} or main
        if: ${{ github.event_name == 'merge_group' }}
        working-directory: ./ussf-portal-client
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.event.merge_group.head_ref}} origin/${{github.event.merge_group.head_ref}} || echo "staying on main"

      - name: Clone cms
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          repository: USSF-ORBIT/ussf-portal-cms
          path: ./ussf-portal-cms
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later
          ref: main # checkout main by default

      - name: Checkout cms ${{github.head_ref}} or main
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        working-directory: ./ussf-portal-cms
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Checkout cms ${{github.event.merge_group.head_ref}} or main
        if: ${{ github.event_name == 'merge_group' }}
        working-directory: ./ussf-portal-cms
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.event.merge_group.head_ref}} origin/${{github.event.merge_group.head_ref}} || echo "staying on main"

      - name: Read Node.js version from package.json
        run: echo "nodeVersion=$(node -p "require('./e2e-tests/e2e/package.json').engines.node")" >> $GITHUB_OUTPUT
        id: engines

      - name: Set up node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # tag=v1
        with:
          aws-access-key-id: ${{ secrets.GHA_ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.GHA_ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.GHA_ECR_ROLE_ASSUMPTION }}
          role-skip-session-tagging: true
          role-duration-seconds: "3600"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261a7de32bda11ba01f4d75c4ed6caf3739e54be # tag=v1

      - uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7 # v2
        id: buildx
        with:
          install: true
          
      - name: Docker compose
        run: docker compose up -d
        working-directory: ./e2e-tests/e2e
        env:
          CMS_REPO: ${{ steps.login-ecr.outputs.registry }}/keystone
          PORTAL_REPO: ${{ steps.login-ecr.outputs.registry }}/portal-client

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./e2e-tests/e2e

      - name: Wait for CMS & Client sysinfo to return 200
        run: yarn wait-on --timeout 60000 http://localhost:3001/api/sysinfo http://localhost:3000/api/sysinfo
        working-directory: ./e2e-tests/e2e

      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: ./e2e-tests/e2e

      - name: Run Playwright tests on ${{ matrix.browser }} browser
        run: yarn e2e:${{ matrix.browser }} --forbid-only
        working-directory: ./e2e-tests/e2e

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: playwright-results
          path: ./e2e-tests/e2e/test-results

      - name: Docker logs
        uses: jwalton/gh-docker-logs@59c9656cd3cb7542525f3dce7ae2f44c0ff85d66 # v2.2.1
        if: ${{ always() }}
        with:
          dest: "./docker-logs"

      - name: Upload logs
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        if: always()
        with:
          name: container-logs
          path: ./docker-logs
