name: Run E2E tests

on:
  # make the workflow reusable
  workflow_dispatch:
  workflow_call:
permissions:
  id-token: write
  contents: read
jobs:
  # run e2e tests on each browser, using build cache from GHA Cache
  run-e2e-tests:
    strategy:
      matrix:
        browser: [ "chromium", "chrome", "msedge" ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone E2E tests repo # defaults to checking out the reference or SHA for the event that triggered this workflow. Otherwise, uses the default branch.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: USSF-ORBIT/ussf-portal
          path: ./e2e-tests
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Checkout E2E ${{github.head_ref}} or main
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && !startsWith(github.head_ref, 'renovate')
        working-directory: ./e2e-tests
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Clone portal client # defaults to checking out the reference or SHA for the event that triggered this workflow. Otherwise, uses the default branch.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: USSF-ORBIT/ussf-portal-client
          path: ./ussf-portal-client
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Checkout portal client ${{github.head_ref}} or main
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && !startsWith(github.head_ref, 'renovate')
        working-directory: ./ussf-portal-client
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Add DoD Certificate Bundle
        env:
          CERT_BUNDLE_SHA256: ${{ secrets.DOD_CA_CERT_BUNDLE_SHA256 }}
        working-directory: ./ussf-portal-client
        run: |
          echo "$CERT_BUNDLE_SHA256" > scripts/dod_ca_cert_bundle.sha256
          sudo bash scripts/add-dod-cas.sh
          
      - name: Clone cms # defaults to checking out the reference or SHA for the event that triggered this workflow. Otherwise, uses the default branch.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: USSF-ORBIT/ussf-portal-cms
          path: ./ussf-portal-cms
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Checkout cms ${{github.head_ref}} or main
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && !startsWith(github.head_ref, 'renovate')
        working-directory: ./ussf-portal-cms
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Clone personnel api # defaults to checking out the reference or SHA for the event that triggered this workflow. Otherwise, uses the default branch.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          repository: USSF-ORBIT/ussf-personnel-api
          path: ./ussf-personnel-api
          fetch-depth: 0 # fetch all branch information, needed to checkout the branch if present later

      - name: Checkout personnel api ${{github.head_ref}} or main
        if: (github.event_name == 'push' || github.event_name == 'pull_request') && !startsWith(github.head_ref, 'renovate')
        working-directory: ./ussf-personnel-api
        run: |
          # checkout the branch that started this pull request or stay on main if no such branch
          /usr/bin/git checkout --progress --force -B ${{github.head_ref}} origin/${{github.head_ref}} || echo "staying on main"

      - name: Read Node.js version from package.json
        run: echo "nodeVersion=$(node -p "require('./e2e-tests/e2e/package.json').engines.node")" >> $GITHUB_OUTPUT
        id: engines

      - name: Set up node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3
        id: buildx
        with:
          install: true

      - name: Restore portal-client Docker build cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        id: restore-client-cache
        with:
          path: /tmp/portal-client
          key: ${{ runner.os }}-docker-portal-client-
          restore-keys: ${{ runner.os }}-docker-portal-client-

      - name: Restore keystone-cms Docker build cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        id: restore-keystone-cache
        with:
          path: /tmp/keystone-cms
          key: ${{ runner.os }}-docker-keystone-cms-
          restore-keys: ${{ runner.os }}-docker-keystone-cms-

      - name: Restore personnel-api Docker build cache
        uses: actions/cache/restore@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        id: restore-personnel-cache
        with:
          path: /tmp/personnel-api
          key: ${{ runner.os }}-docker-personnel-api-
          restore-keys: ${{ runner.os }}-docker-personnel-api-

      - name: Docker compose
        run: |
          docker image prune --all --force
          docker compose up -d
          docker builder prune --all --force
        working-directory: ./e2e-tests/e2e

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./e2e-tests/e2e

      - name: Wait for CMS & Client sysinfo to return 200
        run: yarn wait-on --timeout 60000 http://localhost:3001/api/sysinfo http://localhost:3000/api/sysinfo
        working-directory: ./e2e-tests/e2e

      - name: Install Playwright
        run: npx playwright install --with-deps
        working-directory: ./e2e-tests/e2e

      - name: Run Playwright tests on ${{ matrix.browser }} browser
        run: yarn e2e:${{ matrix.browser }} --forbid-only
        working-directory: ./e2e-tests/e2e

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: playwright-results
          path: ./e2e-tests/e2e/test-results

      - name: Docker logs
        uses: jwalton/gh-docker-logs@59c9656cd3cb7542525f3dce7ae2f44c0ff85d66 # v2.2.1
        if: ${{ always() }}
        with:
          dest: "./docker-logs"

      - name: Upload logs
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: always()
        with:
          name: container-logs
          path: ./docker-logs
