name: Run E2E tests when changed

on:
  # configure on push events
  push:
    branches: [main]
  # configure on pull request events
  pull_request:
    branches: [main]
  # configure on merge group checks
  merge_group:

jobs:
  check-e2e-tests:
    uses: ./.github/workflows/reusable-run-e2e-tests.yml
    secrets: inherit

  lint-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Read Node.js version from package.json
        working-directory: ./e2e
        run: echo "nodeVersion=$(node -p "require('./package.json').engines.node")" >> $GITHUB_OUTPUT
        id: engines

      - name: Set up node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: ${{ steps.engines.outputs.nodeVersion }}

      - name: Get yarn cache directory path
        working-directory: ./e2e
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # The yarn cache is not node_modules
      - name: Install dependencies
        working-directory: ./e2e
        run: yarn --frozen-lockfile

      - name: Lint code
        working-directory: ./e2e
        run: yarn lint
